language: elixir

elixir:
  - '1.5.1'
  - '1.5.2'
  - '1.6.1'
otp_release:
  - '20.1'
services:
  - postgresql
env:
  - MIX_ENV=test

before_script:
  - cp apps/plant_monitor/config/travis.exs apps/plant_monitor/config/test.exs
  - mix ecto.create
  - mix ecto.migrate

script:
  - mix coveralls.travis --umbrella

after_script:
  - bash <(curl -s https://codecov.io/bash)
