language: elixir

elixir:
  - '1.5.2'
otp_release:
  - '20.1'
services:
  - postgresql
env:
  - MIX_ENV=test

script:
  - cp config/travis.exs config/test.exs
  - mix ecto.create
  - mix ecto.migrate
  - mix coveralls.travis

after_script:
  - bash <(curl -s https://codecov.io/bash)
